boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h x86_desc.h lib.h
idt_funcs.o: idt_funcs.c idt_funcs.h lib.h types.h x86_desc.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  idt_funcs.h
lib.o: lib.c lib.h types.h
